default[:cb_tpt][:language][:perl] = '5.20.1'
default[:cb_tpt][:language][:ruby] = '2.3.1'
default[:cb_tpt][:language][:shell] = '4.2'
default[:cb_tpt][:language][:java] = '1.8'
default[:cb_tpt][:language][:groovy] = '2.4.7'
